### ISSUE TITLE
Unable to run the example app: npx pod-install fails.

### ISSUE THREAD

**Issue by buschco** [react-native-community/react-native-slider#223]
## Environment
```
info Fetching system and libraries information...
System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 659.73 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.6, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.6/11E708 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_202 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

## Description

`npx pod-install` runs with errors. Furthermore `yarn run:ios` won't complete.

```
➜ npx pod-install
npx: installed 1 in 1.017s
Scanning for pods...
1.9.3
> pod install
Auto-linking React Native module for target `example`: react-native-slider
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "ReactCommon/jscallinvoker":
  In snapshot (Podfile.lock):
    ReactCommon/jscallinvoker (from `../../node_modules/react-native/ReactCommon`)

  In Podfile:
    ReactCommon/jscallinvoker (from `../../node_modules/react-native/ReactCommon`)

None of your spec sources contain a spec satisfying the dependency: `ReactCommon/jscallinvoker (from `../../node_modules/react-native/ReactCommon`)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    at CocoaPodsPackageManager._installAsync (/Users/colin/.npm/_npx/78146/lib/node_modules/pod-install/build/index.js:2:85721)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)


```
```
➜ yarn run:ios
yarn run v1.22.4
$ react-native run-ios
error Could not find "Podfile.lock" at null.lock. Did you run "pod install" in iOS directory?
error Could not find the following native modules: react-native-slider. Did you forget to run "pod install" ?
info Found Xcode workspace "example.xcworkspace"
info Building (using "xcodebuild -workspace example.xcworkspace -configuration Debug -scheme example -destination id=E34325E5-1147-4A7F-B502-5C564B181E75")
..........
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening example.xcworkspace. Run CLI with --verbose flag for more details.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace example.xcworkspace -configuration Debug -scheme example -destination id=E34325E5-1147-4A7F-B502-5C564B181E75

note: Using new build system
note: Planning build
note: Constructing build description
error: /Users/colin/Documents/code.nosync/react-native-slider/example/ios/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: /Users/colin/Documents/code.nosync/react-native-slider/example/ios/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: /Users/colin/Documents/code.nosync/react-native-slider/example/ios/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')
error: /Users/colin/Documents/code.nosync/react-native-slider/example/ios/Pods/Target Support Files/Pods-example/Pods-example.debug.xcconfig: unable to open file (in target "example" in project "example") (in target 'example' from project 'example')


** BUILD FAILED **


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

## Reproducible Demo

```bash
#!/bin/sh
git clone git@github.com:react-native-community/react-native-slider.git
cd react-native-slider
yarn
cd src
yarn
cd ..
cd example
npx pod-install
yarn run:ios
```

**Comment by buschco** [comment]
It seems that changing 
```ruby
pod 'ReactCommon/jscallinvoker', :path => "#{$node_modules_path}/react-native/ReactCommon"
```
to 
```ruby
pod 'ReactCommon/callinvoker', :path => "#{$node_modules_path}/react-native/ReactCommon"
```
fixes the issue for me.

see https://stackoverflow.com/a/60881827/5444033

**Comment by buschco** [comment]
I created a [PR](https://github.com/react-native-community/react-native-slider/pull/224)

Idk know honestly if it is a good idea to merge it, because of the huge diff in the lockfile, but there is also no way (for the solution I have tried) to prevent the changes.
